version: '3.4'

services:
  postgresql:
    image: postgres:9.6.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  postgres_data:
